- name: Copying the yml directory
  ansible.builtin.copy:
    src: ../K8s/Ingress
    dest: /home/{{ ansible_user }}

- name: applying ingress-controller
  become_user: "{{ ansible_user }}"
  become_method: sudo
  become: true
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /home/{{ ansible_user }}/Ingress/ingress-controller.yml
    - kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
- pause: seconds=20

- name: applying ingress
  become_user: "{{ ansible_user }}"
  become_method: sudo
  become: true
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /home/{{ ansible_user }}/Ingress/ingress.yml -n ingress-nginx
...