
- name: Intilizing Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  run_once: true
- pause: seconds=20

- name: Create directory .kube config
  become_user: "{{ ansible_user }}"
  become_method: sudo
  become: true
  file: 
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config.
  become_user: root
  become_method: sudo
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Create Pod Network
  become_user: "{{ ansible_user }}"
  become_method: sudo
  become: true
  command: "{{ item }}"
  with_items: 
    - kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
- pause: seconds=20  

- name: Get the token for joining the nodes with Kuberentes master.
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
...